#!/bin/bash
# SPDX-License-Identifier: MIT
# Convert client id to hostname and IP address

(ceph tell mds.0 client ls | jq ".[] | select(.id==$1) | .client_metadata.hostname, .entity.addr.addr") |& grep -v ms_handle_reset
